version: "3.8"

services:
  frontend:
    container_name: vue-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # port domyślny dla Vite (Vue 3), zmień na 8080 jeśli używasz Vue CLI
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev # lub: yarn dev
